DROP TABLE IF EXISTS USER_DETAILS;
  
CREATE TABLE USER_DETAILS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email_id VARCHAR(250) DEFAULT NULL
);